### PR TITLE
Python3 support

### PR DESCRIPTION
**Pull request by rc**
Hi Ondrej,

I have made a few changes that allow using dftatom with Python 3. Not sure if Python 2.6 still works, but 2.7 is working.

I did not update `.travis.yml` (yet) - what are your plans with Python 2.6 support?

Cheers,
r.

### CODE REVIEW

**Comment by certik** [comment]
Thanks @rc ! I appreciate it. 

Why don't we switch to pytest? 

Let's remove Python 2.6 support and add Python 3 in Travis. Let me push to your branch.

**Comment by certik** [comment]
Tests pass, merging.

**Comment by rc** [comment]
Thanks for merging! Yes, using pytest is much simpler than maintaining the custom test runner.

I did not know that there is a conda-forge feedstock - does the build include the python interface? I do not see it in the recipe's meta.yaml.

**Comment by certik** [comment]
It doesn't contain the Python interface yet, because Python 3 wasn't working. Now it is, so it should be no problem to include it.

**Pull request merged**
